### ISSUE TITLE
Ads Being Deleted

### ISSUE THREAD

**Issue by xtthew** [ArthurG/Kijiji-Repost-Headless#154] opened 2019-10-27 12:27 UTC
I tried posting Ads with the script, but every time it's posted I'll get the email from Kijiji saying that ad has been posted.. but when I go to look at it, it's been removed. Is there any documentation on how to avoid this happening?

**Comment by vipertemp** [comment] 2019-10-27 13:27
To which category(ies)?

**Comment by xtthew** [comment] 2019-10-27 13:53
To the 'Services > Other' category.

**Comment by vipertemp** [comment] 2019-10-27 14:03
That category would be why.

**Comment by xtthew** [comment] 2019-10-27 14:21
What's wrong with that category? It comes up as a valid option when building the yml

**Comment by vipertemp** [comment] 2019-10-27 14:24
Nothing. I suspect they have set some kind of special condition on that category on the API side that causes this problem.

**Comment by ArthurG** [comment] 2019-10-29 05:14
Duplicate of #112

**Closed by ArthurG** 2019-10-29 05:14 UTC
