### ISSUE TITLE
Using SSID still doesn't login

### ISSUE THREAD

**Issue by yunners** [ArthurG/Kijiji-Repost-Headless#202] opened 2020-11-23 18:29 UTC
I made the changes to the original code to have a separate SSID.txt file just as in the pull.

Got this error:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jmshong/Downloads/Kijiji-Repost-Headless-master/kijiji_repost_headless/__main__.py", line 209, in <module>
    main()
  File "/Users/jmshong/Downloads/Kijiji-Repost-Headless-master/kijiji_repost_headless/__main__.py", line 51, in main
    args.function(args)
  File "/Users/jmshong/Downloads/Kijiji-Repost-Headless-master/kijiji_repost_headless/__main__.py", line 87, in post_ad
    api.login(args.username, args.password)
  File "/Users/jmshong/Downloads/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 129, in login
    raise KijijiApiException("Could not log in.", resp.text)
NameError: name 'resp' is not defined

Is this cookie stealing still working?

**Comment by ArthurG** [comment] 2020-11-25 02:09
This is a duplicate of #198. Please comment on that one instead.

**Closed by ArthurG** 2020-11-25 02:09 UTC
