### ISSUE TITLE
JSON Decoding Error when Posting

### ISSUE THREAD

**Issue by Peppershaker** [ArthurG/Kijiji-Repost-Headless#71] opened 2018-01-29 15:29 UTC
Hey guys,

When I make a post I get the following error.

`Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)

  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "kijiji_repost_headless/__main__.py", line 196, in <module>
    main()

  File "kijiji_repost_headless/__main__.py", line 55, in main
    args.function(args)

  File "kijiji_repost_headless/__main__.py", line 96, in post_ad
    while not check_ad(args) and attempts < 5:

  File "kijiji_repost_headless/__main__.py", line 177, in check_ad
    all_ads = api.get_all_ads()

  File "kijiji_repost_headless/kijiji_api.py", line 216, in get_all_ads
    my_ads_tree = json.loads(my_ads_page.text)

  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)

  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)`

I searched through past issues and it seemed like previously people were getting this error on image upload, however, I'm getting this on posting of ad. The script does not throw any 401 errors.

Any ideas? thanks

**Comment by Peppershaker** [comment] 2018-01-29 15:54
the page that kijiji was trying to look for returned an error page

Hmm... Apparently this page no longer exists.
Most likely the page has been removed or there was a typo in the link.

**Comment by jackm** [comment] 2018-01-29 15:58
This is the same issue as #68.
I already made a [fix for this](https://github.com/ArthurG/Kijiji-Repost-Headless/issues/68#issuecomment-360935458) in my own branch.

...you even replied saying thanks to me yesterday for this?

**Comment by Peppershaker** [comment] 2018-01-29 15:59
yeah i downloaded your fix thought it was the same issue i was getting, tested this morning and still seeing the same thing.... let me try a few more times and report back

**Comment by Peppershaker** [comment] 2018-01-29 16:01
I am a idiot I extracted an old zip this morning. sorry man

**Comment by jackm** [comment] 2018-01-29 16:10
Why not use Git instead of downloading zip files? A simple `git pull` will always make sure that you're up to date with the latest changes. It's kinda the main reason for using a version control system.

**Comment by Peppershaker** [comment] 2018-01-29 16:23
yeah going to start doing that from now on. btw did you find a solution to \n\n not showing up as a blank line?

**Comment by jackm** [comment] 2018-01-29 16:37
Are you talking about #52? No I haven't figured out a fix for that yet. A temporary solution that should work is to just add an additional newline. ie. A double blank line should show up as a single blank line on the ad page after posting.

**Comment by Peppershaker** [comment] 2018-01-29 17:32
okay man. thanks!

**Comment by jackm** [comment] 2018-02-12 01:43
@ArthurG this issue can be closed now. It was a duplicate of #68

**Closed** 2018-02-12 05:37 UTC
