### ISSUE TITLE
Could Not Post Ad

### ISSUE THREAD

**Issue by windowshopr** [ArthurG/Kijiji-Repost-Headless#138] opened 2019-05-09 14:58 UTC
Receive the error:

```
kijiji_repost_headless\__main__.py:67: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f)
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Image upload success on try #1
Traceback (most recent call last):
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kijiji_repost_headless\__main__.py", line 195, in <module>
    main()
  File "kijiji_repost_headless\__main__.py", line 51, in main
    args.function(args)
  File "kijiji_repost_headless\__main__.py", line 95, in post_ad
    api.post_ad_using_data(data, image_files)
  File "kijiji_repost_headless\kijiji_api.py", line 204, in post_ad_using_data
    raise KijijiApiException("Could not post ad.", resp.text)
kijiji_api.KijijiApiException: Could not post ad.
See kijijiapi_dump_20190509T084704.html in current directory for latest dumpfile.
```

Running Python3 on windows 10. Dump file doesn't load. Any ideas?

**Comment by zachatkinson** [comment] 2019-05-10 16:08
Having the exact same problem, and not sure how to diagnose.  Dump file is busted because of XCORS

**Comment by zachatkinson** [comment] 2019-05-12 18:16
I believe this is a duplicate of Issue #112

**Comment by socialcode-rob1** [comment] 2019-06-02 13:03
"YAMLLoadWarning" is not related to "kijiji_api.KijijiApiException: Could not post ad."

You can see the warning doesn't stop the process.  I've opened an issue #139 to track that seperately.
It's pending a PR.

**Comment by jackm** [comment] 2019-06-05 21:06
The dump file is just an HTML text file - you should be able to open it in a browser and view it. Check to see if the Kijiji page shows any error text in red somewhere on the page. This may happen if Kijiji expected to get an additional ad parameter that wasn't passed to it. Some ad postings have additional radio buttons or text fields that aren't automatically included in the yaml ad file.

**Comment by ArthurG** [comment] 2019-06-24 01:00
It's been a while since #139 has been merged. I'm closing this for now. Feel free to re-open if you're still facing the same issue @windowshopr

**Closed by ArthurG** 2019-06-24 01:00 UTC
